version: "3.7"
services:
  web-application-server:
    container_name: web-application-server
    build:
      context: .
      dockerfile: Dockerfile-Migration
    ports:
      - "8080:8080"
    volumes:
      - ../../logs:/var/log/application-logs
    network_mode: host
