name: Delete branch on close pr
on: 
  pull_request:
    types: [ closed ]
    branches: [ develop/be, develop/fe ]
  
jobs:
  delete-branch:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_REPO_PAT }}
